name: Docker Build
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build One
      uses: whoan/docker-build-with-cache-action@v5
      with:
        username: ${{ secrets.DOCKERHUB_NAME }}
        password: ${{ secrets.DOCKERHUB }}
        image_name: fledgre/one-test
        dockerfile: Dockerfile
